/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-26 02:20:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.userPermission;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.model.UserPermission;
import com.htc.airtime.dao.UserPermissionDAO;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.components.Tool;
import com.htc.airtime.model.Account;
import com.htc.airtime.components.Helper;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.model.Account;
import com.htc.airtime.components.Tool;
import com.htc.airtime.dao.AccountDAO;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/userPermission/../includes/mainMenu.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/../includes/footerJs.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/../includes/topMenu.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/common.jsp", Long.valueOf(1513046148000L));
    _jspx_dependants.put("/userPermission/../includes/topFooter.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/../includes/head.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/../includes/../includes/checkLogin.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/userPermission/../includes/breadcrumb.jsp", Long.valueOf(1513046144000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.htc.airtime.components.Tool");
    _jspx_imports_classes.add("com.htc.airtime.dao.UserPermissionDAO");
    _jspx_imports_classes.add("com.htc.airtime.components.Helper");
    _jspx_imports_classes.add("com.htc.airtime.model.UserPermission");
    _jspx_imports_classes.add("com.htc.airtime.model.Account");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.htc.airtime.dao.AccountDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

    String baseUrl = request.getContextPath();
    if (Tool.checkNull(session.getAttribute("acc"))) {
        try {
            response.sendRedirect("/login.jsp");
            return;
        } catch (Exception e) {
            System.out.println("CO LOI NHA");
        }
    }
    String nameUser = "";
    String cpCodeUser = "";
    String checkTypeUser = "";
    int idUser = 0;
    Account acc = null;
    if (!Tool.checkNull(session.getAttribute("acc"))) {
        acc = (Account) session.getAttribute("acc");
        idUser = acc.getAccId();
        nameUser = acc.getUserName();
        cpCodeUser = acc.getCpCode();
        checkTypeUser = AccountDAO.TYPE.getType(acc.getUserType()).toString();
    }

      out.write(' ');
      out.write("<!DOCTYPE html><html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>CMS AirTime [sv1]</title>\n");
      out.write("        <meta charset=\"UTF-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/bootstrap.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/bootstrap-responsive.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/colorpicker.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/datepicker.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/uniform.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/select2.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/maruti-style.css?v=1.0\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/maruti-media.css\" class=\"skin-color\" />\n");
      out.write("        <script src =\"");
      out.print( baseUrl);
      out.write("/resource/js/jquery.min.js\"></script> \n");
      out.write("        <script src =\"");
      out.print( baseUrl);
      out.write("/resource/js/select2.min.js\"></script>\n");
      out.write("        <style>\n");
      out.write("            .checker{\n");
      out.write("                vertical-align: initial;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"header\"><!--Header-part-->\n");
      out.write("            <h1><a href=\"");
      out.print( baseUrl);
      out.write("\">CMS AirTime</a></h1>\n");
      out.write("        </div>");
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");

    String moduleSourse = "userPermission";
    String moduleName = "Phân quyền tài khoản";

      out.write('\n');
      out.write('\n');
      out.write('\n');
  //  
    AccountDAO account = new AccountDAO();
    boolean checkPermission = account.checkList(request, session);
    Helper.cPermission(response, checkPermission);

    String actionName = "Danh sách";

    int idAcc = 0;
    idAcc = Integer.parseInt(request.getParameter("id"));
    UserPermissionDAO userPermission = new UserPermissionDAO();
    ArrayList<UserPermission> dts = userPermission.getListModuleUserPermission(idAcc);


      out.write("\n");
      out.write("\n");
      out.write("<!--close-Header-part--> \n");
      out.write("\n");
      out.write("<!--top-Header-menu-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--top-Header-menu-->\n");
      out.write("<div id=\"user-nav\" class=\"navbar navbar-inverse\">\n");
      out.write("    <ul class=\"nav\">\n");
      out.write("       \n");
      out.write("        <li class=\" dropdown\" id=\"menu-messages\"><a href=\"#\" data-toggle=\"dropdown\" data-target=\"#menu-messages\" class=\"dropdown-toggle\"><i class=\"icon icon-user\"></i> <span class=\"text\">");
      out.print( nameUser);
      out.write(" ---\n");
      out.write("                    ");
      out.print( checkTypeUser);
      out.write("</span> <span class=\"label label-important\">5</span> <b class=\"caret\"></b></a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a class=\"sAdd\" title=\"\" href=\"#\">Xem thông tin user</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"\"><a title=\"\" href=\"");
      out.print( baseUrl);
      out.write("/logout\" onclick=\"return confirm('Bạn có chắc muốn thoát?')\" ><i class=\"icon icon-share-alt\"></i> <span class=\"text\">Logout</span></a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--close-top-Header-menu--> \n");
      out.write("<!--left-menu-stats-sidebar-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    AccountDAO accountPermission = new AccountDAO();

    boolean checkAccounts = true;
    boolean checkUserPermission = true;
    boolean checkModules = true;
    boolean checkServices = true;
    boolean checkAirtimeManager = true;
    boolean checkOtpAirTime = true;
    boolean checkChargeAirTime = true;
    boolean checkErrorOtpAirTime = true;
    boolean checkErrorChargeAirTime = true;

//    checkAccounts = accountPermission.checkList(request, session, "accounts");
//    checkUserPermission = accountPermission.checkList(request, session, "userPermission");
//    checkModules = accountPermission.checkList(request, session, "modules");
//    checkServices = accountPermission.checkList(request, session, "services");
//    checkAirtimeManager = accountPermission.checkList(request, session, "airtimeManager");
//    checkOtpAirTime = accountPermission.checkList(request, session, "otpAirTime");
//    checkChargeAirTime = accountPermission.checkList(request, session, "chargeAirTime");
//    checkErrorOtpAirTime = accountPermission.checkList(request, session, "errorOtpAirTime");
//    checkErrorChargeAirTime = accountPermission.checkList(request, session, "errorChargeAirTime");

      out.write("\n");
      out.write("<div id=\"sidebar\">\n");
      out.write("    <a href=\"#\" class=\"visible-phone\"><i class=\"icon icon-th-list\"></i> Common Elements</a><ul>\n");
      out.write("        <li class=\"active\"><a href=\"/\"><i class=\"icon icon-home\"></i> <span>Trang chủ</span></a> </li>\n");
      out.write("        ");
 if (checkTypeUser.equals("ADMIN") || checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("        <li class=\"submenu\"> <a href=\"#\"><i class=\"icon icon-th-list\"></i> <span>Quản lý</span></a>\n");
      out.write("            <ul>\n");
      out.write("               ");
 if (checkTypeUser.equals("ADMIN") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/accounts\"><i class=\"icon icon-th-list\"></i> <span>Tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/accounts\"><i class=\"icon icon-th-list\"></i> <span>Tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("ADMIN") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/modules\"><i class=\"icon icon-th-list\"></i> <span>Module</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/services\"><i class=\"icon icon-th-list\"></i> <span>Dịch vụ</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/airtimeManager\"><i class=\"icon icon-th-list\"></i> <span>Đăng ký dịch vụ airtime</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/userPermission\"><i class=\"icon icon-th-list\"></i> <span>Phân quyền tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("                <!--//DANH CHO DAI LY-->\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/userPermissionChild\"><i class=\"icon icon-th-list\"></i> <span>Phân quyền tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("\n");
      out.write("        <li class=\"\"> <a href=\"");
      out.print( baseUrl);
      out.write("/reqAll\"><i class=\"icon icon-th-list\"></i> <span>Lịch sử Charging</span> </a>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqOtp\">OTP</a></li>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqCharging\">Charging</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"submenu\"> <a href=\"#\"><i class=\"icon icon-th-list\"></i> <span>Thống kê Charging</span> </a>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqCharging/statistic.jsp\">Charging</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"\"> <a href=\"");
      out.print( baseUrl);
      out.write("/charging\"><i class=\"icon icon-th-list\"></i> <span>Charging</span> </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("</div>");
      out.write("\n");
      out.write("<!--close-left-menu-stats-sidebar-->\n");
      out.write("\n");
      out.write("<div id=\"content\">\n");
      out.write("    <div id=\"content-header\">\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"breadcrumb\"> \n");
      out.write("    <a href=\"/\" title=\"Go to Home\" class=\"tip-bottom\"><i class=\"icon-home\"></i> Trang chủ</a> \n");
      out.write("    <!--nameModule ,nameAction được khai báo bên view action-->\n");
      out.write("    \n");
      out.write("    <a href=\"");
      out.print( baseUrl +"/"+ moduleSourse );
      out.write("\" class=\"tip-bottom\">");
 if(moduleName != ""){out.println(moduleName);
    } 
      out.write("</a> \n");
      out.write("    <a href=\"#\" class=\"current\">");
 if(actionName != ""){out.println(actionName);
    } 
      out.write("</a> \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span12\">\n");
      out.write("                <div class=\"widget-box\">\n");
      out.write("                    <div class=\"widget-title\">\n");
      out.write("                        <span class=\"icon\"><i class=\"icon-th\"></i></span> \n");
      out.write("                        <h5>Danh sách quyền</h5>\n");
      out.write("                        ");
 //if (account.checkList(request, session)) {
      out.write("\n");
      out.write("                        <span class=\"icon\"><a class=\"\" href=\"");
      out.print( baseUrl);
      out.write('/');
      out.print( moduleSourse);
      out.write("\" title=\"Thêm mới\" style=\"padding:0 2px;\">\n");
      out.write("                                <img  width=\"18\" src=\"");
      out.print(baseUrl);
      out.write("/resource/images/icon/home.png\" alt=\"\"> Danh sách</a>\n");
      out.write("                        </span>\n");
      out.write("                        ");
//}
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"widget-content nopadding\">\n");
      out.write("                        <form action=\"");
      out.print( request.getContextPath());
      out.write("/addUserPermission\" name=\"myform\" method=\"post\" class=\"form-horizontal\">\n");
      out.write("                            <input type=\"hidden\" name=\"idAcc\" class=\"span11\" value=\"");
      out.print(idAcc);
      out.write("\" placeholder=\"Id Account\" />\n");
      out.write("                            <table class=\"table table-bordered\">\n");
      out.write("                                <thead>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th>STT</th>\n");
      out.write("                                        <th class=\"hide\">Tên module</th>\n");
      out.write("                                        <th class=\"hide\">Tên module</th>\n");
      out.write("                                        <th class=\"hide\">Tên module</th>\n");
      out.write("                                        <th >Tên module</th>\n");
      out.write("                                        <th >Tên module</th>\n");
      out.write("                                        <th colspan=\"2\">Trạng thái</th>\n");
      out.write("                                        <th colspan=\"8\">Quyền</th>\n");
      out.write("\n");
      out.write("                                        <th>Thực hiện</th>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <tr>\n");
      out.write("                                        <th></th>\n");
      out.write("                                        <th class=\"hide\">ID Module</th>\n");
      out.write("                                        <th class=\"hide\">ID Module</th>\n");
      out.write("                                        <th class=\"hide\">action Module</th>\n");
      out.write("                                        <th>Module</th>\n");
      out.write("                                        <th>Resourse</th>\n");
      out.write("                                        <th >Module</th>\n");
      out.write("                                        <th ><input type=\"checkbox\" class=\"checkAllModule permission\" id=\"permission\" name=\"radios\" /><br>Kích hoạt</th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule all\" id=\"all\" name=\"radios\" /><br>All</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule list\" id=\"list\"  name=\"radios\" /><br>List</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule view\" id=\"view\" name=\"radios\" /><br>Xem</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule add\" id=\"add\" name=\"radios\" /><br>Thêm</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule edit\" id=\"edit\" name=\"radios\" /><br>Sửa</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule delelete\" id=\"delete\" name=\"radios\" /><br>Xóa</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule upload\" id=\"upload\" name=\"radios\" /><br>Upload</span></th>\n");
      out.write("                                        <th ><span><input type=\"checkbox\" class=\"checkAllModule download\" id=\"download\" name=\"radios\" /><br>Download</span></th>\n");
      out.write("\n");
      out.write("                                        <th>\n");
      out.write("                                            <button type=\"submit\" class=\"btn userPermissionSubmit\" name=\"updateOne\" value=\"updateAll\"> <img  width=\"20\" src=\"");
      out.print( baseUrl);
      out.write("/resource/images/icon/update.png\" alt=\"\"> Update all</button>\n");
      out.write("                                        </th>\n");
      out.write("                                    </tr>\n");
      out.write("                                </thead>\n");
      out.write("                                <tbody>\n");
      out.write("                                    ");

                                        int i = 0;
                                        for (UserPermission dt : dts) {
                                            i++;

                                            int idModule = dt.getMODULE_ID();

                                            int statusModule = dt.getSTATUSMODULE();
                                            int isRight = dt.getIS_RIGHT();
                                            String strNameSubmitButton = "";
                                            String nameSubmitButton = "";
                                            String imgSubmitButton = "";
                                            if (isRight == 1) {
                                                nameSubmitButton = "updateOne";
                                                imgSubmitButton = "update";
                                                strNameSubmitButton = "Cập nhật";
                                            } else {
                                                nameSubmitButton = "addOne";
                                                imgSubmitButton = "add";
                                                strNameSubmitButton = "Thêm mới";
                                            }
                                            String imgStatusModule = "";

                                            if (statusModule == 0) {
                                                imgStatusModule = Helper.getImageIcon("inActive", baseUrl);
                                            } else if (statusModule == 1) {
                                                imgStatusModule = Helper.getImageIcon("active", baseUrl);
                                            } else {
                                                imgStatusModule = Helper.getImageIcon("disable", baseUrl);
                                            }
                                            boolean allRight = dt.isALL_RIGHT();
                                            boolean listRight = dt.isLIST_RIGHT();
                                            boolean viewRight = dt.isVIEW_RIGHT();
                                            boolean addRight = dt.isADD_RIGHT();
                                            boolean editRight = dt.isEDIT_RIGHT();
                                            boolean deleteRight = dt.isDEL_RIGHT();
                                            boolean upRight = dt.isUP_RIGHT();
                                            boolean downRight = dt.isDOWN_RIGHT();
                                            int status = dt.getSTATUS();
                                            //checked Right
                                            String checkallRight = "";
                                            String checklistRight = "";
                                            String checkviewRight = "";
                                            String checkaddRight = "";
                                            String checkeditRight = "";
                                            String checkdeleteRight = "";
                                            String checkupRight = "";
                                            String checkdownRight = "";
                                            String checkstatus = "";

                                            if (allRight) {
                                                checkallRight = "checked";
                                            }
                                            if (listRight) {
                                                checklistRight = "checked";
                                            }
                                            if (viewRight) {
                                                checkviewRight = "checked";
                                            }
                                            if (addRight) {
                                                checkaddRight = "checked";
                                            }
                                            if (editRight) {
                                                checkeditRight = "checked";
                                            }
                                            if (deleteRight) {
                                                checkdeleteRight = "checked";
                                            }
                                            if (upRight) {
                                                checkupRight = "checked";
                                            }
                                            if (downRight) {
                                                checkdownRight = "checked";
                                            }
                                            if (status == 1) {
                                                checkstatus = "checked";
                                            }


                                    
      out.write(" \n");
      out.write("                                    <tr class=\"gradeX\" info=\"");
      out.print( nameSubmitButton);
      out.write("\" >\n");
      out.write("                                        <td style=\"width:30px;text-align:center\">");
      out.print( i);
      out.write("</td>\n");
      out.write("                                        <td class=\"hide\">");
      out.print( idModule);
      out.write("</td>\n");
      out.write("                                        <td class=\"hide\">\n");
      out.write("                                            <input type=\"checkbox\"  class=\"checkboxIdModule\" name=\"idModule");
      out.print( idModule);
      out.write("\" value=\"");
      out.print( idModule);
      out.write("\" />\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"hide\">\n");
      out.write("                                            <input type=\"checkbox\"  class=\"checkboxActionModule\" name=\"actionModule");
      out.print( idModule);
      out.write("\" value=\"");
      out.print( nameSubmitButton);
      out.write("\" />\n");
      out.write("                                        </td>\n");
      out.write("                                        <td>");
      out.print( dt.getMODULE_NAME());
      out.write("</td>\n");
      out.write("                                        <td>");
      out.print( dt.getRESOURCE());
      out.write("</td>\n");
      out.write("                                        <td style=\"width:50px;text-align: center;\">\n");
      out.write("                                            <span>\n");
      out.write("                                                ");
      out.print( imgStatusModule);
      out.write("\n");
      out.write("                                            </span>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td style=\"width:50px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkstatus);
      out.write(" class=\"checkRightPermission checkboxpermission\" name=\"status");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkallRight);
      out.write(" class=\"checkRightPermission checkboxall\" title=\"All Right\" name=\"allRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checklistRight);
      out.write(" class=\"checkRightPermission checkboxlist\" title=\"List Right\" name=\"listRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkviewRight);
      out.write(" class=\"checkRightPermission checkboxview\" title=\"View Right\" name=\"viewRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkaddRight);
      out.write(" class=\"checkRightPermission checkboxadd\" title=\"Add Right\" name=\"addRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkeditRight);
      out.write(" class=\"checkRightPermission checkboxedit\" title=\"Edit Right\" name=\"editRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkdeleteRight);
      out.write(" class=\"checkRightPermission checkboxdelete\" title=\"Delete Right\" name=\"deleteRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkupRight);
      out.write(" class=\"checkRightPermission checkboxupload\" title=\"Upload Right\" name=\"upRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:40px;text-align: center;\"><span> <input type=\"checkbox\" ");
      out.print( checkdownRight);
      out.write(" class=\"checkRightPermission checkboxdownload\" title=\"Download Right\" name=\"downRight");
      out.print( idModule);
      out.write("\" /></span></td>\n");
      out.write("                                        <td style=\"width:150px;text-align:center\">\n");
      out.write("                                            <button type=\"submit\" class=\"btn userPermissionSubmit\" name=\"");
      out.print( nameSubmitButton);
      out.write("\" value=\"");
      out.print( idModule);
      out.write("\"> <img  width=\"20\" src=\"");
      out.print( baseUrl);
      out.write("/resource/images/icon/");
      out.print( imgSubmitButton);
      out.write(".png\" alt=\"\"> ");
      out.print( strNameSubmitButton);
      out.write("</button>\n");
      out.write("                                        </td>\n");
      out.write("\n");
      out.write("                                    </tr>\n");
      out.write("                                    ");
 }
      out.write("\n");
      out.write("                                </tbody>\n");
      out.write("                            </table>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<div class=\"row-fluid\">\n");
      out.write("    <div id=\"footer\" class=\"span12\">2017 &copy;. Thiết kế bởi <a href=\"/\">DNH</a> </div>\n");
      out.write("</div>");
      out.write('\n');
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.ui.custom.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap.min.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-colorpicker.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-datepicker.js?v=1.0.0\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.uniform.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.tables.js\"></script>\n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.form_common.js\"></script>\n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.dataTables.min.js?v=1.0.1\"></script> \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        var baseUrl = window.location.origin;\n");
      out.write("        $(\"body\").on(\"click\", '.checkAllModule', function () {\n");
      out.write("            var id = $(this).attr('id');\n");
      out.write("            var checkbox = 'checkbox' + id;\n");
      out.write("            //alert(checkbox);\n");
      out.write("            //$(checkbox)\n");
      out.write("            if ($(this).hasClass('onchecked')) {\n");
      out.write("                $('.' + checkbox).prop('checked', false);\n");
      out.write("                $('.' + checkbox).parent('span').removeClass('checked');\n");
      out.write("\n");
      out.write("//                $('.checkboxIdModule,.checkboxActionModule').prop('checked', false);\n");
      out.write("//                $('.checkboxIdModule,.checkboxActionModule').parent('span').removeClass('checked');\n");
      out.write("\n");
      out.write("                $(this).removeClass('onchecked');\n");
      out.write("            } else {\n");
      out.write("                $('.' + checkbox).prop('checked', true);\n");
      out.write("                $('.' + checkbox).parent('span').addClass('checked');\n");
      out.write("\n");
      out.write("                $('.checkboxIdModule,.checkboxActionModule').prop('checked', true);\n");
      out.write("                $('.checkboxIdModule,.checkboxActionModule').parent('span').addClass('checked');\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                $(this).addClass('onchecked');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"body\").on(\"click\", '.checkRightPermission', function () {\n");
      out.write("            $(this).closest(\"tr\").find('.checkboxIdModule').prop('checked', true);\n");
      out.write("            $(this).closest(\"tr\").find('.checkboxIdModule').parent('span').addClass('checked');\n");
      out.write("            $(this).closest(\"tr\").find('.checkboxActionModule').prop('checked', true);\n");
      out.write("            $(this).closest(\"tr\").find('.checkboxActionModule').parent('span').addClass('checked');\n");
      out.write("        });\n");
      out.write("        $('.userPermissionSubmit').hover(function () {\n");
      out.write("            var nameSubmit = $(this).parent().parent().attr('info');\n");
      out.write("            console.log(nameSubmit);\n");
      out.write("            $(this).attr('name', nameSubmit);\n");
      out.write("        });\n");
      out.write("\n");
      out.write("\n");
      out.write("    });\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
