/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-12-16 03:51:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.accounts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.htc.airtime.components.Tool;
import com.htc.airtime.components.Helper;
import com.htc.airtime.model.Account;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.components.Tool;
import com.htc.airtime.model.Account;
import com.htc.airtime.components.Helper;
import com.htc.airtime.dao.AccountDAO;
import com.htc.airtime.model.Account;
import com.htc.airtime.components.Tool;
import com.htc.airtime.dao.AccountDAO;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/accounts/../includes/topFooter.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/../includes/breadcrumb.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/../includes/head.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/../includes/footerJs.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/../includes/topMenu.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/common.jsp", Long.valueOf(1513046140000L));
    _jspx_dependants.put("/accounts/../includes/../includes/checkLogin.jsp", Long.valueOf(1513046144000L));
    _jspx_dependants.put("/accounts/../includes/mainMenu.jsp", Long.valueOf(1513046144000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.htc.airtime.components.Tool");
    _jspx_imports_classes.add("com.htc.airtime.components.Helper");
    _jspx_imports_classes.add("com.htc.airtime.model.Account");
    _jspx_imports_classes.add("com.htc.airtime.dao.AccountDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\n');

    String baseUrl = request.getContextPath();
    if (Tool.checkNull(session.getAttribute("acc"))) {
        try {
            response.sendRedirect("/login.jsp");
            return;
        } catch (Exception e) {
            System.out.println("CO LOI NHA");
        }
    }
    String nameUser = "";
    String cpCodeUser = "";
    String checkTypeUser = "";
    int idUser = 0;
    Account acc = null;
    if (!Tool.checkNull(session.getAttribute("acc"))) {
        acc = (Account) session.getAttribute("acc");
        idUser = acc.getAccId();
        nameUser = acc.getUserName();
        cpCodeUser = acc.getCpCode();
        checkTypeUser = AccountDAO.TYPE.getType(acc.getUserType()).toString();
    }

      out.write(' ');
      out.write("<!DOCTYPE html><html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>CMS AirTime [sv1]</title>\n");
      out.write("        <meta charset=\"UTF-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/bootstrap.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/bootstrap-responsive.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/colorpicker.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/datepicker.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/uniform.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/select2.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/maruti-style.css?v=1.0\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl);
      out.write("/resource/css/maruti-media.css\" class=\"skin-color\" />\n");
      out.write("        <script src =\"");
      out.print( baseUrl);
      out.write("/resource/js/jquery.min.js\"></script> \n");
      out.write("        <script src =\"");
      out.print( baseUrl);
      out.write("/resource/js/select2.min.js\"></script>\n");
      out.write("        <style>\n");
      out.write("            .checker{\n");
      out.write("                vertical-align: initial;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"header\"><!--Header-part-->\n");
      out.write("            <h1><a href=\"");
      out.print( baseUrl);
      out.write("\">CMS AirTime</a></h1>\n");
      out.write("        </div>");
      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");

    String moduleName = "Tài khoản";
    String moduleSourse  = "accounts";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--close-Header-part--> \r\n");
      out.write("\r\n");
      out.write("<!--top-Header-menu-->\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--top-Header-menu-->\n");
      out.write("<div id=\"user-nav\" class=\"navbar navbar-inverse\">\n");
      out.write("    <ul class=\"nav\">\n");
      out.write("       \n");
      out.write("        <li class=\" dropdown\" id=\"menu-messages\"><a href=\"#\" data-toggle=\"dropdown\" data-target=\"#menu-messages\" class=\"dropdown-toggle\"><i class=\"icon icon-user\"></i> <span class=\"text\">");
      out.print( nameUser);
      out.write(" ---\n");
      out.write("                    ");
      out.print( checkTypeUser);
      out.write("</span> <span class=\"label label-important\">5</span> <b class=\"caret\"></b></a>\n");
      out.write("            <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a class=\"sAdd\" title=\"\" href=\"#\">Xem thông tin user</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"\"><a title=\"\" href=\"");
      out.print( baseUrl);
      out.write("/logout\" onclick=\"return confirm('Bạn có chắc muốn thoát?')\" ><i class=\"icon icon-share-alt\"></i> <span class=\"text\">Logout</span></a></li>\n");
      out.write("    </ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!--close-top-Header-menu--> \r\n");
      out.write("<!--left-menu-stats-sidebar-->\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    AccountDAO accountPermission = new AccountDAO();

    boolean checkAccounts = true;
    boolean checkUserPermission = true;
    boolean checkModules = true;
    boolean checkServices = true;
    boolean checkAirtimeManager = true;
    boolean checkOtpAirTime = true;
    boolean checkChargeAirTime = true;
    boolean checkErrorOtpAirTime = true;
    boolean checkErrorChargeAirTime = true;

//    checkAccounts = accountPermission.checkList(request, session, "accounts");
//    checkUserPermission = accountPermission.checkList(request, session, "userPermission");
//    checkModules = accountPermission.checkList(request, session, "modules");
//    checkServices = accountPermission.checkList(request, session, "services");
//    checkAirtimeManager = accountPermission.checkList(request, session, "airtimeManager");
//    checkOtpAirTime = accountPermission.checkList(request, session, "otpAirTime");
//    checkChargeAirTime = accountPermission.checkList(request, session, "chargeAirTime");
//    checkErrorOtpAirTime = accountPermission.checkList(request, session, "errorOtpAirTime");
//    checkErrorChargeAirTime = accountPermission.checkList(request, session, "errorChargeAirTime");

      out.write("\n");
      out.write("<div id=\"sidebar\">\n");
      out.write("    <a href=\"#\" class=\"visible-phone\"><i class=\"icon icon-th-list\"></i> Common Elements</a><ul>\n");
      out.write("        <li class=\"active\"><a href=\"/\"><i class=\"icon icon-home\"></i> <span>Trang chủ</span></a> </li>\n");
      out.write("        ");
 if (checkTypeUser.equals("ADMIN") || checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("        <li class=\"submenu\"> <a href=\"#\"><i class=\"icon icon-th-list\"></i> <span>Quản lý</span></a>\n");
      out.write("            <ul>\n");
      out.write("               ");
 if (checkTypeUser.equals("ADMIN") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/accounts\"><i class=\"icon icon-th-list\"></i> <span>Tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/accounts\"><i class=\"icon icon-th-list\"></i> <span>Tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("ADMIN") ) {
      out.write("\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/modules\"><i class=\"icon icon-th-list\"></i> <span>Module</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/services\"><i class=\"icon icon-th-list\"></i> <span>Dịch vụ</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/airtimeManager\"><i class=\"icon icon-th-list\"></i> <span>Đăng ký dịch vụ airtime</span></a> </li>\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/userPermission\"><i class=\"icon icon-th-list\"></i> <span>Phân quyền tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("               ");
 if (checkTypeUser.equals("AGENCY_MANAGER") ) {
      out.write("\n");
      out.write("                <!--//DANH CHO DAI LY-->\n");
      out.write("                <li class=\"\"><a href=\"");
      out.print( baseUrl);
      out.write("/userPermissionChild\"><i class=\"icon icon-th-list\"></i> <span>Phân quyền tài khoản</span></a> </li>\n");
      out.write("               ");
}
      out.write("\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("\n");
      out.write("        <li class=\"\"> <a href=\"");
      out.print( baseUrl);
      out.write("/reqAll\"><i class=\"icon icon-th-list\"></i> <span>Lịch sử Charging</span> </a>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqOtp\">OTP</a></li>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqCharging\">Charging</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"submenu\"> <a href=\"#\"><i class=\"icon icon-th-list\"></i> <span>Thống kê Charging</span> </a>\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"");
      out.print( baseUrl);
      out.write("/reqCharging/statistic.jsp\">Charging</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"\"> <a href=\"");
      out.print( baseUrl);
      out.write("/charging\"><i class=\"icon icon-th-list\"></i> <span>Charging</span> </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!--close-left-menu-stats-sidebar-->\r\n");

    //check LIST
    AccountDAO account = new AccountDAO();
    boolean checkPermission = account.checkEdit(request, session);
    Helper.cPermission(response, checkPermission);

    String actionName = "Cập nhật";
    int id = 0;
    int accId = 0;
    int parentId = 0;
    String username = "";
    String fullname = "";
    String description = "";
    String address = "";
    String phone = "";
    String email = "";
    int status = 0;
    
    id = Integer.parseInt(request.getParameter("id"));
    Account dt = new Account();
    dt = account.view(id);

    accId = dt.getAccId();
    username = dt.getUserName();
    fullname = dt.getFullName();
    description = dt.getDescription();
    address = dt.getAddress();
    phone = dt.getPhone();
    email = dt.getEmail();

    status = dt.getStatus();
    parentId = dt.getParentId();

//    if ((checkTypeUser.equals("ADMIN") && ((idUser == accId) || !AccountDAO.TYPE.getType(userType).toString().equals("ADMIN"))) || (checkTypeUser.equals("AGENCY_MANAGER") && ((idUser == accId) || (idUser == parentId)))) {
    if ((checkTypeUser.equals("ADMIN")) || (checkTypeUser.equals("AGENCY_MANAGER") && ((idUser == accId) || (idUser == parentId)))) {
        System.out.println("********TAI KHOAN CUA BAN -DUOC PHEP CAP NHAT TAI KHOAN NAY");
    } else {
        if (checkPermission) {
            response.sendRedirect(request.getContextPath()+'/');
            return;
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("    <div id=\"content-header\">\r\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"breadcrumb\"> \n");
      out.write("    <a href=\"/\" title=\"Go to Home\" class=\"tip-bottom\"><i class=\"icon-home\"></i> Trang chủ</a> \n");
      out.write("    <!--nameModule ,nameAction được khai báo bên view action-->\n");
      out.write("    \n");
      out.write("    <a href=\"");
      out.print( baseUrl +"/"+ moduleSourse );
      out.write("\" class=\"tip-bottom\">");
 if(moduleName != ""){out.println(moduleName);
    } 
      out.write("</a> \n");
      out.write("    <a href=\"#\" class=\"current\">");
 if(actionName != ""){out.println(actionName);
    } 
      out.write("</a> \n");
      out.write("</div>\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row-fluid\">\r\n");
      out.write("            <div class=\"span7 offset2\">\r\n");
      out.write("                <div class=\"widget-box\">\r\n");
      out.write("                    <div class=\"widget-title\"> <span class=\"icon\"> <i class=\"icon-align-justify\"></i> </span>\r\n");
      out.write("                        <h5>");
      out.print( actionName);
      out.write("</h5>\r\n");
      out.write("                        <h5>\r\n");
      out.write("                            ");

                                if (!Tool.checkNull(request.getAttribute("err"))) {
                                    out.println(request.getAttribute("err"));
                                }
                            
      out.write("\r\n");
      out.write("                        </h5>\r\n");
      out.write("                        ");
 if (account.checkList(request, session)) {
      out.write("\r\n");
      out.write("                        <span class=\"icon\"><a class=\"\" href=\"");
      out.print( baseUrl);
      out.write('/');
      out.print( moduleSourse);
      out.write("\" title=\"Danh sách tài khoản\" style=\"padding:0 2px;\">\r\n");
      out.write("                                ");
      out.print( Helper.getImageIcon("home", baseUrl));
      out.write(" Danh sách</a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                        ");
 if (account.checkAdd(request, session)) {
      out.write("\r\n");
      out.write("                        <span class=\"icon\"><a class=\"\" href=\"");
      out.print( baseUrl);
      out.write('/');
      out.print( moduleSourse);
      out.write("/add.jsp\" title=\"Thêm mới tài khoản\" style=\"padding:0 2px;\">\r\n");
      out.write("                                ");
      out.print( Helper.getImageIcon("add", baseUrl));
      out.write(" Thêm mới</a>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        ");
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"widget-content nopadding\">\r\n");
      out.write("                        <form action=\"");
      out.print( baseUrl);
      out.write("/updateAcc\" name=\"myform\" method=\"post\" class=\"form-horizontal\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"hidden\" name=\"accId\" class=\"span11\" value=\"");
      out.print(accId);
      out.write("\" placeholder=\"Id Account\" />\r\n");
      out.write("                            <input type=\"hidden\" name=\"parentId\" class=\"span11\" value=\"");
      out.print(parentId);
      out.write("\" placeholder=\"parentId\" />\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Tài khoản :</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"text\" readonly=\"readonly\"  name=\"username\" onchange=\"checkUserName(this)\" class=\"span11\" value=\"");
      out.print(username);
      out.write("\" placeholder=\"Nhập tài khoản\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Mật khẩu</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"password\" name=\"password\"  class=\"span11\" placeholder=\"Nhập mật khẩu\"  />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Họ Tên :</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"text\" name=\"fullname\" class=\"span11\" value=\"");
      out.print(fullname);
      out.write("\" placeholder=\"Nhập họ tên\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Miêu tả:</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <textarea class=\"span11\" name=\"description\" placeholder=\"Nhập miêu tả.\" >");
      out.print(description);
      out.write("</textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Địa chỉ :</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"text\" name=\"address\" class=\"span11\" value=\"");
      out.print(address);
      out.write("\" placeholder=\"Nhập địa chỉ\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Điện thoại :</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"text\" name=\"phone\" class=\"span11\" value=\"");
      out.print(phone);
      out.write("\" placeholder=\"Nhập số điện thoại\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Email :</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <input type=\"text\" name=\"email\" class=\"span11\" value=\"");
      out.print(email);
      out.write("\" placeholder=\"Nhập số email\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Loại tài khoản</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("\r\n");
      out.write("                                    ");
    //                                    
                                        if (checkTypeUser.equals("ADMIN")) {

                                    
      out.write("\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"userType\" value=\"");
      out.print(AccountDAO.TYPE.ADMIN.val);
      out.write('"');
      out.write(' ');

                                            if (dt.getUserType() == AccountDAO.TYPE.ADMIN.val) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                        ");
      out.print( AccountDAO.TYPE.getname(AccountDAO.TYPE.ADMIN.val) );
      out.write("\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                                    ");
    //                                    
                                        if (checkTypeUser.equals("ADMIN") || (checkTypeUser.equals("AGENCY_MANAGER") && idUser == accId)) {

                                    
      out.write("\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"userType\" value=\"");
      out.print(AccountDAO.TYPE.AGENCY_MANAGER.val);
      out.write('"');
      out.write(' ');

                                            if (dt.getUserType() == AccountDAO.TYPE.AGENCY_MANAGER.val) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                       ");
      out.print( AccountDAO.TYPE.getname(AccountDAO.TYPE.AGENCY_MANAGER.val) );
      out.write("\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                                    ");

                                        if (checkTypeUser.equals("ADMIN") || checkTypeUser.equals("AGENCY_MANAGER")) {
                                    
      out.write("\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"userType\" value=\"");
      out.print(AccountDAO.TYPE.AGENCY.val);
      out.write('"');
      out.write(' ');

                                            if (dt.getUserType() == AccountDAO.TYPE.AGENCY.val) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                        ");
      out.print( AccountDAO.TYPE.getname(AccountDAO.TYPE.AGENCY.val) );
      out.write("\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"userType\" value=\"");
      out.print(AccountDAO.TYPE.USER.val);
      out.write('"');
      out.write(' ');

                                            if (dt.getUserType() == AccountDAO.TYPE.USER.val) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                        ");
      out.print( AccountDAO.TYPE.getname(AccountDAO.TYPE.USER.val) );
      out.write("\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    ");
}
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <label class=\"control-label\">Trạng thái</label>\r\n");
      out.write("                                <div class=\"controls\">\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"status\" value=\"1\" ");

                                            if (status == 1) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                        Kích hoạt</label>\r\n");
      out.write("                                    <label>\r\n");
      out.write("                                        <input type=\"radio\" name=\"status\" value=\"0\"");

                                            if (status == 0) {
                                                out.print("checked");
                                            }
                                               
      out.write(" />\r\n");
      out.write("                                        Không kích hoạt</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-actions\">\r\n");
      out.write("                                <button type=\"submit\" name=\"addAccount\" class=\"btn btn-success\">Lưu</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<div class=\"row-fluid\">\n");
      out.write("    <div id=\"footer\" class=\"span12\">2017 &copy;. Thiết kế bởi <a href=\"/\">DNH</a> </div>\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.ui.custom.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap.min.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-colorpicker.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-datepicker.js?v=1.0.0\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.uniform.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.js\"></script> \n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.tables.js\"></script>\n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.form_common.js\"></script>\n");
      out.write("    <script src =\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.dataTables.min.js?v=1.0.1\"></script> \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
