/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-08 09:29:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.htc.airtime.components.Tool;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/layoutLogin/header.jsp", Long.valueOf(1509441466000L));
    _jspx_dependants.put("/includes/layoutLogin/footer.jsp", Long.valueOf(1509441466000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.htc.airtime.components.Tool");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
 
    String baseUrl = request.getContextPath();
//    Helper helper = new Helper();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>AirTime</title>\n");
      out.write("  <meta charset=\"<?= Yii::$app->charset ?>\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/bootstrap.min.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/bootstrap-responsive.min.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/colorpicker.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/datepicker.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/uniform.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/select2.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/maruti-style.css?v=1.2\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( baseUrl );
      out.write("/resource/css/maruti-media.css\" class=\"skin-color\" />\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!--Header-part-->\n");
      out.write("<div id=\"header\">\n");
      out.write("  <h1><a href=\"dashboard.html\">AriTime</a></h1>\n");
      out.write("</div>\n");
      out.write("<!--close-Header-part--> \n");
      out.write('\n');
    
    if (!Tool.checkNull(session.getAttribute("acc"))) {
        response.sendRedirect(request.getContextPath());
    }

      out.write("\n");
      out.write("<style>\n");
      out.write("    .help-block{\n");
      out.write("        color: #d81b1b;\n");
      out.write("        display: inline-block;\n");
      out.write("    }\n");
      out.write("</style>\n");
    String usename = "";
    String password = "";
    String remember = "";

    if (!Tool.checkNull(request.getParameter("username"))) {
        usename = request.getParameter("username");
    }
    if (!Tool.checkNull(request.getParameter("remember"))) {
        remember = "checked='checked'";
    }


      out.write("\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("    <div class=\"row-fluid\">\n");
      out.write("        <div class=\"span6 offset3\">\n");
      out.write("            <div class=\"widget-box\">\n");
      out.write("                <div class=\"widget-title\"  >\n");
      out.write("                    <h5 style=\"width: 100%; text-align: center\">Đăng nhập</h5>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"widget-content nopadding\">\n");
      out.write("\n");
      out.write("                    <form action=\"");
      out.print( baseUrl);
      out.write("/login\" name=\"myform\" method=\"post\" class=\"form-horizontal\">\n");
      out.write("                        <div class=\"control-group\">\n");
      out.write("                            <label class=\"control-label\">Tài khoản :</label>\n");
      out.write("                            <div class=\"controls\">\n");
      out.write("                                <input type=\"text\" value=\"");
      out.print( usename);
      out.write("\" name=\"username\" onchange=\"checkUserName(this)\" class=\"span11\" placeholder=\"Nhập tài khoản\" />\n");
      out.write("                                <div class=\"help-block\">\n");
      out.write("                                    ");

                                        if (!Tool.checkNull(session.getAttribute("mess"))) {
                                    
      out.write("\n");
      out.write("                                    ");
      out.print( session.getAttribute("mess"));
      out.write("\n");
      out.write("                                    ");

                                            session.setAttribute("mess", null);
                                        }
                                    
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"control-group\">\n");
      out.write("                            <label class=\"control-label\">Mật khẩu</label>\n");
      out.write("                            <div class=\"controls\">\n");
      out.write("                                <input type=\"password\" name=\"password\"  class=\"span11\" placeholder=\"Nhập mật khẩu\"  />\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"control-group\">\n");
      out.write("                            <label class=\"control-label\"></label>\n");
      out.write("                            <div class=\"controls\">\n");
      out.write("                                <label>\n");
      out.write("                                    <input type=\"checkbox\" name=\"remember\" ");
      out.print( remember);
      out.write("/>\n");
      out.write("                                    Nhớ mật khẩu</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-actions\">\n");
      out.write("                            <button type=\"submit\" name=\"loginForm\" class=\"btn btn-success\">Đăng nhập</button>\n");
      out.write("                            <sapn style=\"margin-left: 20px;\"><a href=\"\">Quên mật khẩu</a></sapn>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("\n");
      out.write("                    <div class=\"control-group\">\n");
      out.write("                        <label class=\"control-label\"></label>\n");
      out.write("                        <div class=\"controls\">\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <?php ActiveForm::end(); ?>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.min.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.ui.custom.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap.min.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-colorpicker.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/bootstrap-datepicker.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/jquery.uniform.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/select2.min.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.js\"></script> \n");
      out.write("  <script src=\"");
      out.print( baseUrl );
      out.write("/resource/js/maruti.form_common.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
